### ISSUE TITLE
add a `conda.recipes` directory

### ISSUE THREAD

**Issue by phobson** [Geosyntec/pygridtools#26]

**Comment by ocefpaf** [comment]
I just added a recipe for pygridtools in the [ioos channel](https://github.com/ioos/conda-recipes/commit/bb6c59b8fd0f76aa7aa8e9a9c93d9884a03bbbf1).

Would you consider reducing the number dependencies for the packages?  For example: you have `seaborn` and `bokeh`, which I guess are cosmetic deps and could be optional, right?

**Comment by phobson** [comment]
closing as IOOS takes care of this
