### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'sort' in iotools.py

### ISSUE THREAD

**Issue by fpacheco** [Geosyntec/pygridtools#58]
Great work!. 

Sort is obsolete in pandas package, must use sort_values:

-  return df[cols].sort(columns='order') -> return df[cols].sort_values(by='order')
- df.sort(inplace=True) -> df.sort_values(inplace=True)

Thank you. Regards. Fernando.

**Comment by phobson** [comment]
Thanks for the report. I've got a collection of fixes and changes in the works. I'll be sure to include this.

**Comment by Ketki-Savle** [comment]
Thank you. changing it from "sort" to "sort_values" helped!

**Comment by bora-pajo** [comment]
How can I do value_counts() and sort_values() at the same time?  Trying to do cumulative sum and cumulative percent on variables but I need them sorted first. Renaming the sorted variables did not work

**Comment by phobson** [comment]
@bora-pajo that's a pandas question, not a pygridtools question.
