### ISSUE TITLE
Problem with importing the package

### ISSUE THREAD

**Issue by khajehei** [Geosyntec/pygridtools#63]
Hello,
I am getting the following errors while I am importing. I would be grateful if you can help me with that.

   import pygridtools as pgt
  File "/home/sepideh/anaconda3/lib/python3.5/site-packages/pygridtools/__init__.py", line 2, in <module>
    from .core import *
  File "/home/sepideh/anaconda3/lib/python3.5/site-packages/pygridtools/core.py", line 9, in <module>
    from pygridtools import iotools
  File "/home/sepideh/anaconda3/lib/python3.5/site-packages/pygridtools/iotools.py", line 11, in <module>
    import fiona
  File "/home/sepideh/anaconda3/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/sepideh/anaconda3/lib/python3.5/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /home/sepideh/anaconda3/lib/python3.5/site-packages/fiona/../../.././libkea.so.1.4: undefined symbol: _ZN2H56H5FileC1ERKSsjRKNS_17FileCreatPropListERKNS_15FileAccPropListE

**Comment by phobson** [comment]
Looks like a fiona/gdal binary issue.

Try a fresh environment where you get *everythin* from conda-forge:
```
conda create --name=grid pygridtools geopandas fiona --channel=conda-forge
```

**Comment by phobson** [comment]
Oops, you'll need to specify a python version, make that:
```
conda create --name=grid python=3.6 pygridtools geopandas fiona --channel=conda-forge
```

**Comment by khajehei** [comment]
I get this when I am trying:

UnsatisfiableError: The following specifications were found to be in
conflict:
  - pygridtools -> python=2.7
  - python=3.6

**Comment by phobson** [comment]
Try python 3.5 then. I need to update the conda-forge builds, but that won't happen for a while.

**Comment by khajehei** [comment]
Thanks, it is working now.

**Comment by phobson** [comment]
Python 3.6 build available via: https://github.com/conda-forge/pygridtools-feedstock/pull/7
