### ISSUE TITLE
Saving the products as shapefile

### ISSUE THREAD

**Issue by khajehei** [Geosyntec/pygridtools#65]
I want to save the grids as shapefiles. I cannot understand what is the template shapefile and how I should create that.

**Comment by phobson** [comment]
Do you want to write the nodes (as point) or the cells (as polygons)?

The version of pygridtools in conda-forge dispatches the shapefile writing to the fiona package:
https://toblerity.org/fiona/manual.html#writing-new-files

You need a template (existing) shapefile that defines the output schema, CRS, etc. It's not the most elegant, but that's how it works right now.

We're moving away from this approach to utilize geopandas more. 
http://geopandas.org/

If you want to write the nodes, you could use the the output from `ModelGrid.to_dataframe` method to construct a geopandas.GeoDataFrame object and quickly dump that to a shapefile,

**Comment by phobson** [comment]
As an example, if you had a grid, `g`, and wanted to save the nodes as a shapefile with geopandas, you'd do this:
```python
from shapely.geometry import Point
import geopandas
gdf = (g
 .to_dataframe()
 .stack(level='ii')
 .reset_index()
 .assign(geometry=lambda df: df.apply(lambda row: Point(row['easting'], row['northing']), axis=1))
 .pipe(geopandas.GeoDataFrame)
)

gdf.to_file(...)
```

**Comment by khajehei** [comment]
Great, it worked!

Thanks,
Sepideh
