### ISSUE TITLE
Create ipywidgets UI to manipulate Focus objects

### ISSUE THREAD

**Issue by phobson** [Geosyntec/pygridtools#83]
For this round of TAC funding, we need to write a function that returns an ipywidgets UI that helps users manipulate the focus objects associated with grids.

In #81, I wrote a function that returns two sliders that manipulate the shape (as in resolution) of the grid. We can use that as a starting point.

ipywidgets docs are here: https://ipywidgets.readthedocs.io/en/stable/

This is a difficult problem to solve from a user-experience perspective. The `focus` parameter is that is passed to a the `Gridgen` constructor is an arbitrarily-sized collection of `_FocusPoint` objects, which take 4 parameter: (location, axis, factor (strength), extent).

So it'd be nice to have a way to dynamically add a new `_FocusPoint` to the main `focus` parameter, but the first step is to build a UI that manipulates a single `_FocusPoint`.

Need a brush up on grid focus? Check out:
1. [the existing docs](https://pygridgen.github.io/pygridgen/tutorial/basics.html#Using-focus)
2. [this demo notebook](https://gist.github.com/phobson/ee6384cfada1136d5bbb44bc4c992f1b)

**Comment by lucashtnguyen** [comment]
@kqasem I'm on this one. I've got a working demo in a notebook and I'm cleaning it up for a PR.
